name: yoka_tech_pro
description: YOKA TECH Pro mobile shop management app
publish_to: "none"
version: 3.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  printing: ^5.14.2
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
